### PR TITLE
Strapi v5 compatibility

### LINKED ISSUE #24: with AzureAD, getting data undefined
Response data contains:

```
...
data: {
  sub: '1Ridu4nBBowBa1UBQdGxruNOEt4tihf3y3Yd1GtfIPE',
  name: 'Yanick LANDRY (EXT)',
  family_name: 'LANDRY',
  given_name: 'Yanick',
  picture: 'https://graph.microsoft.com/v1.0/me/photo/$value'
}
```

I think it is because my provider is not using OIDC. I will fix by adding an option configurable via config

### LINKED ISSUE #58: Strapi 5 Support
Thank you for this awesome plugin, it's working great.

[Strapi 5 just got to RC stage](https://strapi.io/blog/the-strapi-5-release-candidate-is-here), do you plan on supporting Strapi 5 down the road?

I've ran into some issues using your strapi-plugin-sso@0.4.5 with @strapi/strapi@5.0.0-rc.7.

### PR DESCRIPTION
**Pull request by marc0777**
Support for Strapi v5, currently tested on RC11, fixes #58.

I set it as draft as there are a few things that I have to look into. I tested it with Autentik and it was working correctly, now looking into testing it with AzureAD (probably will need to also fix #24 for that to work).

Will update it as soon as I as I have news, with also a bit of explanation on how to use this, since since Strapi v5 plugins should be built.

### CODE REVIEW

**Comment by delemeator** [comment]
#24 should not be an issue as long as users have email defined in AzureAD. The problem is that email is just not mandatory in Azure AD

**Comment by marc0777** [comment]
@delemeator yes you're right, I was having a similar problem but it was unrelated (using an HTTPS proxy is broken in axios/https and that was causing the request to fail and therefore the SSO fail in the same way as described in that issue).

I was able to test it with AzureAD and have been using the updated extension without problems on Strapi v5 RC11 for a few days now. 

@yasudacloud do you prefer to wait for Strapi to release the first stable version before merging or to merge this into the branch and keep that updated?

**Comment by yasudacloud** [comment]
@marc0777 
Hello!
Thanks for all the commits.

I would like to make some changes to the v5 branch on my end, so I would like to merge it once, is that OK?

**Comment by marc0777** [comment]
I haven't written here anymore because since RC18 the plugin stopped working, and it doesn't run with the stable version either. 
I wasn't able to figure out what changed and I'm having problems also running the examples given by the Strapi team. I've since opened an issue regarding this, https://github.com/strapi/sdk-plugin/issues/60.

If you want to merge and start working on it yourself feel free to do so! :)

Just a couple of notes:
- some parts weren't included in the PR so far, so take a deep look at the diff
- according to the new SDK plugins should now be built, all commands to be used are already in the `package.json`

I'll be available in case you need more information.

**Comment by yasudacloud** [comment]
@marc0777 
Thank you for sharing the details.
I would like to proceed based on your commitments.

By the way, regarding [strapi/sdk-plugin#60](https://github.com/strapi/sdk-plugin/issues/60) , I encountered a similar error while writing another plugin in TypeScript.
At that time, using dynamic imports solved the issue.

**Comment by marc0777** [comment]
Yes, using dynamic imports worked here too but it looks like an hack and I hope it's not the approach "officially" recommended by Strapi.

**Comment by marc0777** [comment]
Hello, I've refactored the plugin to use ES Module syntax, now all imports are working correctly and the syntax is much cleaner too.

I've tested this in Strapi 5.0.1 and everything seems to be working!

**Comment by yasudacloud** [comment]
@marc0777 
Thanks so much for the PR!!
I checked it works on my end as well and the build went through and I was able to log in with each provider.

However, there were a few things I wanted to fix, so I will try to fix them on my end as well.

**Pull request merged**
